USE [master]
GO

/****** Object:  Database [Morskie perevozki]    Script Date: 09.02.2022 15:56:06 ******/
CREATE DATABASE [Morskie perevozki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Morskie perevozki', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Morskie perevozki.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Morskie perevozki_log', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Morskie perevozki_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Morskie perevozki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Morskie perevozki] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Morskie perevozki] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Morskie perevozki] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Morskie perevozki] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Morskie perevozki] SET ARITHABORT OFF 
GO

ALTER DATABASE [Morskie perevozki] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Morskie perevozki] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Morskie perevozki] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Morskie perevozki] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Morskie perevozki] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Morskie perevozki] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Morskie perevozki] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Morskie perevozki] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Morskie perevozki] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Morskie perevozki] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Morskie perevozki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Morskie perevozki] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Morskie perevozki] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Morskie perevozki] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Morskie perevozki] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Morskie perevozki] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Morskie perevozki] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Morskie perevozki] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Morskie perevozki] SET  MULTI_USER 
GO

ALTER DATABASE [Morskie perevozki] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Morskie perevozki] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Morskie perevozki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Morskie perevozki] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Morskie perevozki] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Morskie perevozki] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Morskie perevozki] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Morskie perevozki] SET  READ_WRITE 
GO


